import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Button} from 'react-bootstrap'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paste Bucket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/paste-buckets.jpg" />
      </Head>
      <h1>Welcome to Paste Bucket</h1>
      <p>
        This is an application for people to upload and share snippets of text
      </p>
      <Button
        href="/create-snippet" 
        variant="outline-success"
        >
        Create Snippet</Button>

    </div>
  )
}
